#!/bin/bash

# scripted by: Alaa-Atwa
# this script calculate "total time of a course you have locally on your machine"
# Navigate to your course folder and run this script 

# You can add the script to your $PATH :
# > cp tcourse /usr/bin/
# > source ~/.bashrc 

# Colors
# to access colors as variables: echo ${RED}Colored_red_here
C=$(printf '\033') # you must use this line before using any color
RED="${C}[1;31m"
SED_RED="${C}[1;31m&${C}[0m"
GREEN="${C}[1;32m"
SED_GREEN="${C}[1;32m&${C}[0m"
YELLOW="${C}[1;33m"
SED_YELLOW="${C}[1;33m&${C}[0m"
SED_RED_YELLOW="${C}[1;31;103m&${C}[0m"
BLUE="${C}[1;34m"

# Banner
if [[ `command -v figlet` ]];then
  figlet "Tcourse"
  echo "scripted by: ${BLUE} Alaa-Atwa"
fi

# check for the required tools
required_tools=(exiftool vi awk)

for cmd in ${required_tools[@]};do
  if [[ ! $(command -v $cmd) ]]; then
    echo "You Must install $cmd first"
    exit 1
  fi
done

echo "${GREEN}===================================================================="
echo "${BLUE}     Calculating, Please Wait ,it may takes a while !"
echo "${GREEN}=====================================================================" 

# getting videos
format=(mp4 mkv mov avi flv wmv webm mpeg-4) # add the video format if not listed

for ext in ${format[@]};do
    find . -type f  -iname "*.$ext" >> /tmp/videos.txt
done

cat /tmp/videos.txt | while read line; do
  exiftool "$line" | grep "Media Duration" | cut -d":" -f"3" >> /tmp/mins.txt
  exiftool "$line" | grep "Media Duration" | cut -d":" -f"4" >> /tmp/seconds.txt 
done


awk '{ sum += $1} END { print sum }' /tmp/mins.txt > /tmp/allminutes.txt
awk '{ sum += $1} END { print sum }' /tmp/seconds.txt > /tmp/allseconds.txt

# converting seconds into minutes
s=$(cat /tmp/allseconds.txt)
mis=$((s/60))
ts=$(( s-mis*60 ))
# exiftool extract the real duration in seconds .. so it may differ in calculating the total seconds

#converting minutes into hours 
m=$(cat /tmp/allminutes.txt)
M=$(( m+mis))

hours=$((M/60))
mins=$(( M-hours*60))

echo -e " \n ${GREEN}total time is ${RED}$hours hours , ${BLUE}$mins minutes and ${YELLOW}$ts seconds \n " | tee total_course_time.txt

rm -rf /tmp/mins.txt /tmp/allminutes.txt /tmp/seconds.txt /tmp/allseconds.txt /tmp/videos.txt  
