#!/bin/bash
# Scripted By: Alaa-Atwa
# this is a simple timer to calculate time passed since you executed this script 

# Colors
# to access variables echo ${RED}Colored_red_here
C=$(printf '\033') # you must use this line before using any color
RED="${C}[1;31m"
SED_RED="${C}[1;31m&${C}[0m"
GREEN="${C}[1;32m"
SED_GREEN="${C}[1;32m&${C}[0m"
YELLOW="${C}[1;33m"
SED_YELLOW="${C}[1;33m&${C}[0m"
BOLD='\033[1m'
SED_RED_YELLOW="${C}[1;31;103m&${C}[0m"
BLUE="${C}[1;34m"
#--------------------------------------------------------------------# 
sec=0
min=0
hour=0

if (( $# > 1 ));then
  echo "Usage: ./`basename $0` [title_for_the_timer] "
  echo "If title contains spaces use double quotes \"title\""
  exit 0
fi

if [[  -n "$1" ]];then
  title="$1"
  # checking if "figlet" is not installed it will skip using this command 
  if [[ $(command -v figlet) ]];then
    clear # comment this line if you don't want to clear the screen
    figlet -f banner -w 60 $title
   echo "Scripted by: Alaa-Atwa "
   echo 
 else
   clear # comment this line if you don't want to clear the screen 
   echo "============== Timer For: $title ==========================="
   echo
  fi
fi

if (( $# == 0 ));then
  echo "*Note: You can provide a title for your timer by running : ./timer [title]"
fi

while true;do
  printf "Time Passed is ${RED}$hour hour/s, ${BLUE}$min minute/s and ${GREEN}$sec second/s ..\r" # \r will overwrite the previous line, making only one line appears
  sec=$[ $sec + 1 ]
  if (( $sec == 60 ));then
    min=$[ $min +1 ]
    sec=0
  fi
  if (( $min == 60 ));then
    hour=$[ $hour + 1 ]
    min=0
  fi
  sleep 1
done

